sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.yarn"
    - ./node_modules

before_install:
  - yarn

jobs:
  include:
    - stage: lint
      php: 5.6
      script:
        - ./bin/lint.sh

    - stage: lint
      php: 7.2
      script:
        - ./bin/lint.sh
